Check that seg fault doesn't occur by doing:

    ./loop.sh

which will loop through many runs of `python test_en.py`.
